#!/bin/bash

###
### ATTENTION! ATTENTION! ATTENTION!
###     This file is managed by Puppet.
###     Any local modifications will be lost in the next puppet run.
### ATTENTION! ATTENTION! ATTENTION!
###

# Sincronismo de horario
/usr/sbin/ntpdate -s 172.16.1.5
/usr/sbin/ntpdate -s 172.16.1.6

# vim:ft=sh

